### ISSUE TITLE
[BUG] - Multiply-rooted property tree exception

### ISSUE THREAD

**Issue by melaasar** [opencaesar/owl-adapter#61]
This context of this bug is here: https://github.com/opencaesar/community/discussions/18

When running the oml2owl on the following vocabulary:
```
	aspect TitledElement

	scalar property hasTitle [
		domain TitledElement
		range xsd:string
	]

	aspect NamedElement

	scalar property Name [
		domain NamedElement
		range xsd:string
	]

	aspect LocalNamed :> TitledElement

	scalar property hasLocalName :> hasTitle, Name [
		domain LocalNamed
		range xsd:string
	]
```

we get the exception:
```
Caused by: java.lang.UnsupportedOperationException: multiply-rooted property tree
	at io.opencaesar.oml2owl.CloseDescriptionBundle.lambda$getPropertyTrees$37(CloseDescriptionBundle.java:377)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.opencaesar.oml2owl.CloseDescriptionBundle.getPropertyTrees(CloseDescriptionBundle.java:372)
	at io.opencaesar.oml2owl.CloseDescriptionBundle$CloseDescriptionBundleToOwl.run(CloseDescriptionBundle.java:745)
```

**Comment by melaasar** [comment]
Fixed in 1.4.4
